spring:
  application:
    name: Mini-Dooray-8-task
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace

server:
  port: 8082